# Generated by Django 5.2.3 on 2025-08-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='intent_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='last_intent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
